DataApp/config/routes.rb
DataApp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  match '/businesses/list_restaurants' => 'businesses#list_restaurants'

  match '/:controller/:action(/:food(/:operation))'

   root :to => 'static#home'
 

end

DataApp/app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.order(:name).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business }
    end
  end

  def list_restaurants
    puts "here"
    dish = params[:dish]
    lat = params[:lat]
    long = params[:long]
    if lat.count < 2 and long.count < 2
      lat = lat.first.to_f
      long = long.first.to_f
    else
      list_multiple_places(lat, long)
      return
    end
    list = []
    category = Category.where(:name => "Restaurants").first
    businesses = Business.near_location(lat, long, 0.05)
    if dish
      food = FoodItem.where(:name => dish.downcase).first()
      if food
        businesses = Business.where(:business_id => food.businesses_ids)
      end
    end
    businesses.keep_if{|x| x.categories.include?(category)}.take(15).each do |b|
      if list.length < 15
        puts "here"
        hash = {}
        hash["name"] = b.name
        hash["rating"] = b.stars
        hash["address"] = b.full_address.gsub("\n", " ")[0..60]
        hash["latlng"] = [b.latitude, b.longitude]
        hash["generosity"] = b.generosity
        hash["url"] = b.url
        list << hash
      else
        break
      end
    end
    list.sort!{|x,y| (x["lat"].to_f-lat+x["long"].to_f-long).abs <=> (y["lat"].to_f-lat+y["long"].to_f-long).abs}
    puts list
    render json: {results: list}
  end


  def list_multiple_places(lats, longs)
    big_list = []
    category = Category.where(:name => "Restaurants").first
    lats.zip(longs).each do |coords|
      list = []
      lat = coords[0].to_f
      long = coords[1].to_f
      puts [lat, long].inspect
      businesses = Business.near_location(lat, long, 0.02)
      businesses.uniq.keep_if{|x| x.categories.include?(category)}.take(15).each do |b|
        puts "here"
        hash = {}
        hash["name"] = b.name
        hash["rating"] = b.stars
        hash["address"] = b.full_address.gsub("\n", " ")[0..60]
        hash["latlng"] = [b.latitude, b.longitude]
        hash["generosity"] = b.generosity
        hash["url"] = b.url
        list << hash
        puts list.inspect
      end
      list.sort!{|x,y| (x["lat"].to_f-lat+x["long"].to_f-long).abs <=> (y["lat"].to_f-lat+y["long"].to_f-long).abs}
      big_list << list
    end
    puts big_list.flatten
    render json: {results: big_list.flatten}
  end

  def list_by_meal
    puts "here"
    lat = params[:lat].to_f
    long = params[:long].to_f
    dishes = params[:dishes]
    category = Category.where(:name => "Restaurants").first
    retval = []
    used = []
    dishes.each do |dish|
      food = FoodItem.where(:name => dish.downcase).first()
      puts food
      if food
        b = Business.where(:business_id => food.businesses_ids).keep_if{|x| x.categories.include?(category)}
        puts b.inspect
        b.sort!{|x,y| (x.latitude-lat+x.longitude-long).abs <=> (y.latitude-lat+y.longitude-long).abs}
        while used.include?(b.first) do
          b.shift
        end
        used << b.first
        if b.first
          hash = {}
          hash["name"] = b.first.name
          hash["rating"] = b.first.stars
          hash["address"] = b.first.full_address.gsub("\n", " ")[0..60]
          hash["generosity"] = b.first.generosity
          hash["latlng"] = [b.first.latitude, b.first.longitude]
          retval << hash
        end
      end
    end
    render json: {results: retval}
  end

end

DataApp/app/helpers/businesses_helper.rb
module BusinessesHelper
end

DataApp/app/views/businesses/_form.html.erb
<%= form_for @business, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :business_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :business_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :full_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :full_address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :schools, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :schools, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :open, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :open, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :categories, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :categories, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :review_count, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :review_count, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :neighborhoods, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :neighborhoods, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stars, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :stars, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :latitude, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                businesses_path, :class => 'btn' %>
  </div>
<% end %>

DataApp/app/views/businesses/edit.html.erb
<%- model_class = Busines -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

DataApp/app/views/businesses/index.html.erb
<%- model_class = Business -%>
<div class="container-fluid">
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
    </div>
    <div>
        <%= paginate @businesses %>
    </div>
    <table class="table table-striped span12">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:business_id) %></th>
          <th><%= model_class.human_attribute_name(:full_address) %></th>
          <th><%= model_class.human_attribute_name(:open) %></th>
          <th><%= model_class.human_attribute_name(:photo_url) %></th>
          <th><%= model_class.human_attribute_name(:city) %></th>
          <th><%= model_class.human_attribute_name(:review_count) %></th>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:url) %></th>
          <th><%= model_class.human_attribute_name(:longitude) %></th>
          <th><%= model_class.human_attribute_name(:state) %></th>
          <th><%= model_class.human_attribute_name(:stars) %></th>
          <th><%= model_class.human_attribute_name(:latitude) %></th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @businesses.each do |business| %>
          <tr>
            <td><%= link_to business.id, business_path(business) %></td>
            <td><%= business.business_id %></td>
            <td><%= business.full_address %></td>
            <td><%= business.open %></td>
            <td><%= business.photo_url %></td>
            <td><%= business.city %></td>
            <td><%= business.review_count %></td>
            <td><%= business.name %></td>
            <td><%= business.url %></td>
            <td><%= business.longitude %></td>
            <td><%= business.state %></td>
            <td><%= business.stars %></td>
            <td><%= business.latitude %></td>
            <td><%=l business.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

DataApp/app/views/businesses/new.html.erb
<%- model_class = Busines -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

DataApp/app/views/businesses/show.html.erb
<%- model_class = Business -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:business_id) %>:</strong></dt>
  <dd><%= @business.business_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:full_address) %>:</strong></dt>
  <dd><%= @business.full_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:schools) %>:</strong></dt>
  <dd><%= @business.schools %></dd>
  <dt><strong><%= model_class.human_attribute_name(:open) %>:</strong></dt>
  <dd><%= @business.open %></dd>
  <dt><strong><%= model_class.human_attribute_name(:categories) %>:</strong></dt>
  <dd><%= @business.categories %></dd>
  <dt><strong><%= model_class.human_attribute_name(:photo_url) %>:</strong></dt>
  <dd><%= @business.photo_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @business.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:review_count) %>:</strong></dt>
  <dd><%= @business.review_count %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @business.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighborhoods) %>:</strong></dt>
  <dd><%= @business.neighborhoods %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @business.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @business.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @business.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stars) %>:</strong></dt>
  <dd><%= @business.stars %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @business.latitude %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              businesses_path, :class => 'btn'  %>
</div>